# Kustomization file for the development environment.
#
# - Inherits resources from the base configuration.
# - Sets the namespace to 'zkvote-dev' and prefixes resource names with 'dev-'.
# - Applies a common label 'environment: development' to all resources.
# - Merges deployment patches for frontend and backend from the 'patches' directory.
# - Generates or merges ConfigMaps for frontend and backend using files from the 'config' directory.
# - Overrides container images for frontend and backend to use the 'dev' tag from GitHub Container Registry.
apiVersion: kustomize.config.k8s.io/v1beta1 # Kustomize version (v1beta1 is stable)
kind: Kustomization # specifies this is a Kustomization file
resources: # List of resources to include
  - ../base
namespace: zkvote-dev # Namespace for the resources
namePrefix: dev- # Prefix for all resource names
commonLabels: # Common labels to apply to all resources
  environment: development

patchesStrategicMerge: # Patches to apply to the resources
  - patches/frontend-deployment-patch.yaml # Patch for the frontend deployment
  - patches/backend-deployment-patch.yaml # Patch for the backend deployment

configMapGenerator: # ConfigMap generation
  - name: frontend-config # Name of the ConfigMap
    behavior: merge # Merge behavior for existing ConfigMaps
    files: # Files to include in the ConfigMap
      - config/frontend-configmap.yaml # Path to the frontend configmap file
  - name: backend-config # Name of the ConfigMap
    behavior: merge # Merge behavior for existing ConfigMaps
    files: # Files to include in the ConfigMap
      - config/backend-configmap.yaml # Path to the backend configmap file

images: # Image overrides
  - name: ghcr.io/zkvote/frontend # Name of the image to override
    newTag: dev # New tag for the image
  - name: ghcr.io/zkvote/backend # Name of the image to override
    newTag: dev # New tag for the image
