# This ConfigMap provides configuration data for the frontend application in the production environment.
# - NODE_ENV: Specifies the environment in which the frontend is running (set to "production").
# - API_URL: Defines the base URL for the backend API that the frontend communicates with.
apiVersion: v1 # API version for the ConfigMap resource
kind: ConfigMap # Kind of resource
metadata: # Metadata for the ConfigMap resource
  name: frontend-config # Name of the ConfigMap
data: # Data for the ConfigMap
  NODE_ENV: "production" # Environment mode for the frontend, set to "production"
  API_URL: "https://api.zkvote.io"  # Base URL for the backend API that the frontend will use for communication
