# This kustomization.yaml configures the production environment for the zkVote application.
# It builds on the base configuration, applying production-specific settings:
# - Sets the namespace to 'zkvote-prod' and prefixes resource names with 'prod-'.
# - Adds a common label 'environment: production' to all resources.
# - Applies strategic merge patches to customize frontend and backend deployments.
# - Merges additional configuration files into frontend and backend ConfigMaps.
# - Updates the frontend and backend container images to use the 'prod' tag.
apiVersion: kustomize.config.k8s.io/v1beta1 # Kustomize version (v1beta1 is stable)
kind: Kustomization # specifies this is a Kustomization file
resources: # List of resources to include
  - ../base # Base configuration for the application
namespace: zkvote-prod # Namespace for the application
namePrefix: prod- # Prefix for all resource names
commonLabels: # Common labels to apply to all resources
  environment: production # Label to indicate this is the production environment
patchesStrategicMerge: # Patches to apply to the resources
  - patches/frontend-deployment-patch.yaml # Patch for the frontend deployment
  - patches/backend-deployment-patch.yaml # Patch for the backend deployment
configMapGenerator: # ConfigMap generation
  - name: frontend-config # Name of the ConfigMap for frontend
    behavior: merge # Merge behavior for existing ConfigMaps
    files: # Files to include in the ConfigMap
      - config/frontend-configmap.yaml # Path to the frontend configmap file
  - name: backend-config # Name of the ConfigMap for backend
    behavior: merge # Merge behavior for existing ConfigMaps
    files: # Files to include in the ConfigMap
      - config/backend-configmap.yaml # Path to the backend configmap file
images: # Image overrides for the production environment
  - name: ghcr.io/zkvote/frontend # Name of the image to override
    newTag: prod # New tag for the image
  - name: ghcr.io/zkvote/backend # Name of the image to override
    newTag: prod # New tag for the image
