name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Decrypt zkey file
        run: |
          mkdir -p keys
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ZKEY_PASSPHRASE }}" \
            --output keys/voting_0001.zkey keys/voting_0001.zkey.gpg

      - name: Build Docker image
        run: docker build --build-arg ZKEY_PASSPHRASE=${{ secrets.ZKEY_PASSPHRASE }} -t zkvote:latest .

      - name: Run Docker Compose
        run: |
          ZKEY_PASSPHRASE=${{ secrets.ZKEY_PASSPHRASE }} docker compose up --build -d
          sleep 10
          docker compose logs
          docker compose down

      - name: Cleanups
        run: |
          docker system prune -f
          docker volume prune -f
          docker network prune -f
